s = str(input("nhập vào một chuỗi: "))
b = s.strip()
a = b.capitalize()   
s_sub = str(input("nhập vào một chuỗi con: "))
counts = s.count(s_sub)
s_find = str(input("nhập vào một chuỗi cần tìm: "))
s_replace = str(input("nhập vào một chuỗi cần thay thế: "))
print("Chuỗi: ",s)
print("số lần xuất hiện chuỗi con là: ",counts)
print("chuỗi sau khi tìm kiếm và thay thế :", a.replace(s_find,s_replace))
